// Per-buddy personality dialogue banks + context-aware picker.
// Placeholders supported in lines: {subject} {topic} {task} {mins} {streak} {xp} {level} {due}
const D = {
mochi:{
open:["hey. i'm here, you're here, that's already a win.","no pressure — just open the book when you're ready.","level {level} and still showing up. that's the whole game.","take a breath. we'll figure out the rest together."],
start:["okay, {subject} time. i've got you.","{topic} it is. nice and steady.","locking in for {mins} minutes. you don't have to rush it.","let's just start. the rest sorts itself out."],
pause:["totally fine. pausing is part of studying too.","take your time. i'll keep the spot warm.","no guilt here. breathe, then come back."],
resume:["okay, welcome back. same page, same energy.","let's pick it right back up.","glad you're back. nothing was lost."],
complete:["that's a session in the bank. proud of you.","{mins} minutes of real focus. that counts.","however that felt, you showed up. that's what matters."],
milestone30:["30 minutes in. you're doing genuinely well.","that's a real chunk of focus. nice."],
milestone60:["an hour of studying. that's not small.","sixty minutes deep. take a proper breather after this."],
longSession:["you've been at this a while — remember to drink some water.","this is a long one. still with me? take a break if you need it."],
taskDone:["one less thing on your plate. good.","'{task}' — done. that's a weight off."],
manyTasks:["there's a lot sitting on your list. we don't have to do it all today.","let's just pick one task off this pile and start there."],
deadline:["'{task}' is due {due}. no panic, just a plan.","heads up — {task} is coming up on {due}. want to tackle it now?"],
streak:["{streak} days in a row. that's consistency, not luck.","{streak}-day streak. quietly impressive."],
levelUp:["level {level} now. look at that.","you leveled up. that's real progress adding up."],
buyReward:["treat yourself, you earned that.","nice pick. you worked for those XP."],
water:["good, don't forget to actually drink water too.","hydration check — proud of you for logging that."],
lowStudy:["no study logged yet today, and that's okay. even five minutes counts.","whenever you're ready, i'm not going anywhere."],
idle:["just checking in. no pressure to do anything right now.","i'm here whenever you want to start."],
quizCorrect:["yep, exactly right.","that's it. you know this better than you think."],
quizWrong:["close, but not quite — here's what it actually is.","not this time, that's okay, let's look at the answer together."]
},
boba:{
open:["OKAY we are so back. let's gooo.","brain.exe please launch, we have things to do.","the syllabus is looking at us. rude behavior on our part honestly.","zero motivation but full attendance, let's see what happens."],
start:["{subject} lock-in engaged. no side quests. main quest only.","{topic}?? okay let's make this chapter regret existing.","{mins} minutes. the procrastination arc ends HERE.","we lockin' for {mins} min, no explanation needed."],
pause:["pause accepted, snack break is a valid strategy.","okay break time, don't @ me.","pausing is basically self care, we love that for us."],
resume:["aaaand we're back. dramatic re-entry complete.","okay resuming, pretend the last 5 minutes didn't happen.","back on our academic villain arc."],
complete:["{mins} minutes DOWN. that's a certified W.","session complete, we ate that up honestly.","okay that's enough side quests for today, good job."],
milestone30:["30 minutes?? okay academic weapon.","half an hour deep, we're actually cooking."],
milestone60:["AN HOUR. who even are you right now.","60 minutes in, certified lockin behavior."],
longSession:["okay this is a whole era of studying, go get water pls.","we've been here a hot minute, stretch or something."],
taskDone:["'{task}' is OFFICIALLY defeated. rest in peace.","one task down, the assignment had no chance."],
manyTasks:["the task list is giving chaos ngl, let's just pick one.","okay we have a whole situation happening on this list, one at a time."],
deadline:["'{task}' due {due}, the deadline is approaching at suspicious speeds.","{due} for {task}?? okay that snuck up on us."],
streak:["{streak} day streak, we are him.","{streak} days straight, unbothered, moisturized, studying."],
levelUp:["LEVEL {level} LETS GOOO.","we leveled up, main character moment."],
buyReward:["okay purchase secured, treat yourself bestie— wait i said bestie. anyway congrats.","new item unlocked, we deserve nice things."],
water:["hydration arc continues, respect.","water logged, staying hydrated AND smart, iconic."],
lowStudy:["okay 0 minutes today is crazy but there's still time.","the syllabus is patient. barely. let's fix this."],
idle:["just vibing here waiting for you tbh.","no pressure just standing here looking cute."],
quizCorrect:["okay smarty, that's correct.","yes!! see you knew that."],
quizWrong:["ehh not quite, but no shame in the game.","wrong answer but A for effort, here's the real one."]
},
niko:{
open:["let's not waste time. what's first.","ready when you are.","level {level}. good. keep the pace."],
start:["{subject}. focus in.","{mins} minutes. full attention, starting now.","no distractions. begin."],
pause:["paused. don't let it become an hour.","fine. come back with intent."],
resume:["good. back to it.","resume. no more delay."],
complete:["{mins} minutes logged. solid work.","done. that effort was real."],
milestone30:["30 minutes. acceptable pace, keep going.","half hour in. don't stop now."],
milestone60:["an hour of focus. that's discipline.","60 minutes. this is what consistency looks like."],
longSession:["you've been at this a while. don't burn out, take a break after this.","long session. stay sharp, don't push past useful."],
taskDone:["'{task}' — finished. move to the next.","done. that's one less excuse."],
manyTasks:["your list is long. pick one and start. now.","stop looking at the whole list. one task."],
deadline:["'{task}' is due {due}. handle it before it becomes a problem.","{due}. that's not far. start now."],
streak:["{streak} days straight. that's discipline, not luck.","{streak}-day streak. don't break it over nothing."],
levelUp:["level {level}. earned, not given.","level up. proof the work is working."],
buyReward:["fine, you've earned it. don't get comfortable.","reward claimed. back to work after this."],
water:["good. hydration matters for focus too.","noted. now back to studying."],
lowStudy:["nothing logged yet today. that changes now.","zero minutes so far. let's fix that immediately."],
idle:["waiting. say the word.","ready when you decide to start."],
quizCorrect:["correct. as expected.","right. you know this material."],
quizWrong:["incorrect. here's the actual answer — remember it.","wrong, but now you know. don't repeat it."]
},
pudding:{
open:["hi! however today's going, i'm glad you're here.","no rush at all. we'll take it one small step at a time.","let's start gently today, okay?"],
start:["okay, {subject} time. you've got this, i promise.","{topic}, nice — one small step forward.","{mins} minutes, and that's more than enough for now."],
pause:["that's completely okay. rest when you need to.","pausing isn't quitting. take your time."],
resume:["yay, welcome back! let's continue together.","okay, picking right back up. no worries at all."],
complete:["{mins} minutes of real effort — that's wonderful.","you did it! however small it felt, it counts.","so proud of you for finishing that."],
milestone30:["30 minutes! that's genuinely something to be proud of.","half an hour of focus — amazing work."],
milestone60:["a whole hour! you should be really proud right now.","60 minutes of effort. incredible, honestly."],
longSession:["you've worked hard today — please remember to rest a little.","this has been a long session, take care of yourself after this."],
taskDone:["'{task}' is done — yay, one less worry!","you finished it! that's such good progress."],
manyTasks:["the list looks long, but we don't have to do it all at once.","let's just gently pick one thing to start with."],
deadline:["just a gentle reminder — '{task}' is due {due}.","'{task}' is coming up on {due}. we've got time if we start now."],
streak:["{streak} days in a row — that's such lovely consistency.","{streak}-day streak! you're building something really good."],
levelUp:["you leveled up to {level}! that's amazing, congratulations.","level {level} now — look how far you've come."],
buyReward:["aw, enjoy your new reward, you really earned it.","that's so nice — treat yourself, you deserve it."],
water:["yay, staying hydrated too! take care of yourself.","good job logging your water, that matters too."],
lowStudy:["no study yet today, and that's completely alright.","whenever you're ready, even five minutes is a lovely start."],
idle:["just here quietly, whenever you're ready.","no pressure at all — i'm not going anywhere."],
quizCorrect:["yes, that's exactly right! well done.","you got it! see, you knew that."],
quizWrong:["that's alright, not quite — here's the answer, no worries at all.","close! here's the correct one, you'll get it next time."]
},
luna:{
open:["let's make today count. what are we aiming for?","big things start with today's session. let's go.","today is a good day to start strong."],
start:["{subject}, locked in. let's push forward.","{topic} — let's actually master this, not just get through it.","{mins} minutes of pure momentum, starting now."],
pause:["okay, quick pause. don't lose the momentum though.","pausing — but we're coming right back stronger."],
resume:["back and ready. let's keep building.","resuming with full energy. let's go."],
complete:["{mins} minutes closer to your goals. that's progress.","done, and that's momentum you can carry forward."],
milestone30:["30 minutes — that's real traction. keep pushing.","half an hour of focused work. building something here."],
milestone60:["a full hour. that's the kind of work that adds up big.","60 minutes deep — this is how goals get hit."],
longSession:["big session today. make sure you refuel after this one.","that's serious focus. take a real break once you're done."],
taskDone:["'{task}' — crushed it. onto the next goal.","done. that's one more step toward the bigger picture."],
manyTasks:["big list, but big lists just mean big potential. pick one and start.","let's turn this list into a plan, one task at a time."],
deadline:["'{task}' is due {due} — let's get ahead of it, not behind it.","{due} for {task}. plenty of time if we start now."],
streak:["{streak}-day streak. that's the kind of consistency that wins.","{streak} days straight — you're building real momentum."],
levelUp:["level {level}! that's earned, and there's more ahead.","leveled up. this is just the beginning."],
buyReward:["nice, you earned that — keep stacking wins.","reward secured. that's what progress looks like."],
water:["good, staying fueled matters for peak performance too.","hydration logged. taking care of the whole system."],
lowStudy:["nothing yet today — let's change that and start strong.","zero minutes so far, but the day's still ours to win."],
idle:["ready whenever you are. let's make moves.","standing by for the next big push."],
quizCorrect:["exactly right — that's the kind of knowledge that sticks.","yes! that's what mastery looks like."],
quizWrong:["not quite, but that's how we find the gaps — here's the answer.","missed that one, now you know it for next time."]
},
cloudie:{
open:["hi... taking things slow and soft today, okay?","whenever you're ready, no rush at all.","let's drift into studying gently today."],
start:["okay... {subject}, let's settle into it.","{topic}, softly and steadily.","{mins} minutes, like a quiet little pocket of time."],
pause:["mm, pausing. let the thoughts settle for a bit.","that's alright. rest a little."],
resume:["okay... continuing gently from here.","back again. let's keep drifting through this."],
complete:["{mins} minutes of quiet focus. that was lovely, honestly.","done. that felt like a peaceful little session."],
milestone30:["30 minutes... that's a soft little victory.","half an hour of calm focus. nice."],
milestone60:["a whole hour, quietly. that's really something.","60 minutes... you stayed with it. that's nice to see."],
longSession:["it's been a while now... maybe rest your eyes for a bit after this.","long session... don't forget to breathe and stretch."],
taskDone:["'{task}'... done. one less cloud in the sky.","that's finished now. nice and clear."],
manyTasks:["the list feels heavy, i know. let's just drift to one thing.","so many little things... let's just pick the nearest one."],
deadline:["'{task}' is due {due}... just a gentle little reminder.","{due} is coming for {task}. no rush, just awareness."],
streak:["{streak} days... quietly, steadily, you kept going.","{streak}-day streak. soft consistency, really lovely."],
levelUp:["level {level}... look at that, quietly amazing.","you leveled up. that's a nice little milestone."],
buyReward:["ooh, nice. enjoy that little treat.","that's sweet, you deserve something nice."],
water:["water logged... taking care of yourself softly too.","good, staying hydrated, quietly important."],
lowStudy:["nothing yet today... that's okay, the day is still open.","no study logged, but there's still time to drift into it."],
idle:["just floating here quietly, whenever you're ready.","no pressure... i'll just be here."],
quizCorrect:["mm, yes, that's right.","that's it exactly, well done."],
quizWrong:["not quite... here's the answer, gently.","close, but here's the real one, no worries."]
},
peach:{
open:["hiii! so happy you're here, let's make today good!","yay, ready to start? let's gooo!","today's going to be a good study day, i can feel it!"],
start:["{subject} time, yay!","{topic}! let's have a great session!","{mins} minutes of awesome focus, here we go!"],
pause:["okay, quick break, that's totally fine!","pausing for a sec, you deserve it!"],
resume:["yay you're back! let's keep the good vibes going!","okay, picking back up, let's finish strong!"],
complete:["{mins} minutes done, that's amazing!!","yay, session complete! so proud of you!"],
milestone30:["30 minutes, woohoo!!","half an hour in, you're on fire!"],
milestone60:["a whole HOUR, that's incredible!!","60 minutes, you're absolutely crushing it!"],
longSession:["wow, long session, remember to grab some water though!","you've been going strong, take a happy little break soon!"],
taskDone:["'{task}' done, yesss!!","yay, one task down, you're on a roll!"],
manyTasks:["ooh big list, but we can totally handle it one at a time!","lots to do, but let's just pick one and go, you've got this!"],
deadline:["'{task}' is due {due}, let's get ahead of it, yay teamwork!","just a heads up, {task} is due {due}, we can totally do this!"],
streak:["{streak} days in a row, that's amazing!!","{streak}-day streak, you're on fire!"],
levelUp:["LEVEL {level}!! yay congratulations!!","you leveled up, that's so exciting!!"],
buyReward:["yay new stuff! enjoy it, you totally earned it!","ooh nice pick! treat yourself!"],
water:["yay hydration! love that for you!","water logged, staying healthy and smart!"],
lowStudy:["no study yet today, but that's okay, let's start now, yay!","today's still wide open, let's make it a good one!"],
idle:["hii just here being cheerful, whenever you're ready!","no pressure, just cheering you on from here!"],
quizCorrect:["yesss that's right!!","woo you got it!!"],
quizWrong:["aw, close! here's the answer though, you'll get it next time!","not quite, but that's okay, here's the real one!"]
},
smokey:{
open:["hey.","here if you need me.","let's see how today goes."],
start:["{subject}. alright.","{topic}. sure, let's do that.","{mins} minutes. fine by me."],
pause:["paused. fine.","okay. taking a break, i guess."],
resume:["back. cool.","resuming. let's go, quietly."],
complete:["{mins} minutes. that's a session.","done. not bad."],
milestone30:["30 minutes. that's actually solid.","half an hour. respect."],
milestone60:["an hour. huh. impressive, honestly.","60 minutes. didn't expect that, but nice."],
longSession:["long one. drink some water at some point.","been a while. take a break when you can."],
taskDone:["'{task}'. done. moving on.","finished. good."],
manyTasks:["long list. pick one, ignore the rest for now.","lots of tasks. one at a time, that's it."],
deadline:["'{task}' due {due}. just so you know.","{due}. that's coming up, in case you forgot."],
streak:["{streak} days. quietly impressive.","{streak}-day streak. you're not slowing down, huh."],
levelUp:["level {level}. there it is.","leveled up. cool."],
buyReward:["got yourself something. nice.","reward claimed. enjoy it, i guess."],
water:["water logged. good.","hydration noted."],
lowStudy:["nothing today yet. no rush though.","zero minutes so far. whenever."],
idle:["still here.","no pressure. just around."],
quizCorrect:["yep. correct.","right. figured you'd know that."],
quizWrong:["nope. here's the answer.","wrong one. that's the real answer, for next time."]
},
pika:{
open:["OKAY HI let's GOOO what are we doing today!!","ready ready ready, let's start already!!","okay okay let's just start, i can't wait!"],
start:["{subject}!! okay let's gooo!!","{topic}, ooh interesting, let's dive in!!","{mins} minutes, easy, let's just DO it!!"],
pause:["okay pause, quick, but come baaack!!","pausing, okay okay, be right here!!"],
resume:["YOU'RE BACK let's gooo again!!","okay okay resuming, let's finish this!!"],
complete:["{mins} minutes done, that was awesome!!","yesss session complete, let's celebrate for like two seconds and then go again!!"],
milestone30:["30 MINUTES let's gooo!!","half an hour, we're on a roll!!"],
milestone60:["AN HOUR omg you're unstoppable!!","60 minutes, that's SO much focus, wow!!"],
longSession:["okay this has been a while, go get water quick then come back!!","long session, quick stretch break then let's keep going!!"],
taskDone:["'{task}' DONE let's gooo, next one!!","yesss task defeated, onto the next!!"],
manyTasks:["ooh big list, okay okay let's just pick one and gooo!!","lots to do, that's fine, one at a time, let's start!!"],
deadline:["'{task}' due {due}!! okay we gotta move on this!!","heads up heads up, {task} is due {due}!!"],
streak:["{streak} days!! that's SO cool, keep it going!!","{streak}-day streak, you're on fire, let's gooo!!"],
levelUp:["LEVEL {level} LETS GOOO THAT'S SO COOL!!","omg you leveled up!! amazing!!"],
buyReward:["ooh new thing!! let's see it, let's see it!!","yay you bought something, enjoy enjoy!!"],
water:["water!! yay staying hydrated, love that!!","okay water logged, let's keep going!!"],
lowStudy:["okay nothing yet today but that's fine, let's start NOW!!","zero minutes, okay, let's fix that, let's gooo!!"],
idle:["okay just waiting here, kinda bouncing off the walls ngl!!","ready whenever, i literally cannot sit still!!"],
quizCorrect:["YES that's right omg!!","you got it!! let's gooo next one!!"],
quizWrong:["ooh close but not quite, here's the answer!!","nope, but that's okay, here's the real one, let's keep going!!"]
},
berry:{
open:["okay, let's get organized. what's the plan today?","good, you're here — let's make a plan and stick to it.","let's set today up properly from the start."],
start:["{subject}, logged and starting now.","{topic}, noted. let's stay on track.","{mins} minutes, timer set, let's not waste it."],
pause:["fine, pausing — but let's keep this short.","paused. don't let it drift too long, okay?"],
resume:["good, back on schedule. let's continue.","resuming. right on track."],
complete:["{mins} minutes logged properly. exactly how it should be.","done, and recorded. that's how we do it."],
milestone30:["30 minutes, right on target. nice and organized.","half an hour, tracked and accounted for."],
milestone60:["a full hour, logged. very on-schedule of you.","60 minutes. that's a properly productive block."],
longSession:["long session — make sure you actually take the break you've earned.","that's a big block of time. schedule a proper rest after this."],
taskDone:["'{task}' — checked off. exactly where it should be.","done. crossing that off the list, as planned."],
manyTasks:["okay, this list needs prioritizing. let's rank it and start.","lots on here — let's just tackle the most urgent one first."],
deadline:["'{task}' is due {due}. that needs to go on today's plan.","{due}. let's schedule {task} in before it becomes urgent."],
streak:["{streak} days, right on schedule. very consistent of you.","{streak}-day streak, exactly the kind of routine that works."],
levelUp:["level {level}, logged and earned properly.","leveled up. the system is working, clearly."],
buyReward:["purchase logged. good use of your XP.","nice, that's a well-earned reward, properly tracked."],
water:["water logged, good, staying on top of everything.","hydration tracked. very organized of you."],
lowStudy:["nothing logged yet today — let's fix that and get on schedule.","zero minutes so far, that's not like you, let's start now."],
idle:["standing by, ready to log the next session whenever.","here and organized, whenever you're ready to start."],
quizCorrect:["correct, exactly as expected.","right. good, that's properly understood."],
quizWrong:["not quite — let's note the correct answer for next time.","incorrect, but now it's logged so you won't miss it again."]
}
};
function pick(arr){return arr[Math.floor(Math.random()*arr.length)]}
export function say(buddyId, category, ctx={}){
  const bank = D[buddyId] || D.mochi;
  const pool = bank[category] || D.mochi[category] || ["..."];
  let line = pick(pool);
  line = line.replace(/\{(\w+)\}/g,(_,k)=> (ctx[k]!==undefined&&ctx[k]!==null&&ctx[k]!=='') ? ctx[k] : '');
  return line.replace(/\s{2,}/g,' ').trim();
}
export const buddyTraits = {
mochi:'calm + supportive', boba:'chaotic + playful', niko:'serious + direct', pudding:'gentle + wholesome',
luna:'ambitious + confident', cloudie:'dreamy + soft', peach:'cheerful + enthusiastic', smokey:'quiet + deadpan',
pika:'hyper + curious', berry:'organized + productive'
};
